update sband to work correctly

diff --git a/circuit-python-passthrough/Makefile b/circuit-python-passthrough/Makefile
--- a/circuit-python-passthrough/Makefile
+++ b/circuit-python-passthrough/Makefile
@@ -20,17 +20,17 @@ install: ## Install passthrough code to board. Usage: make install sband BOARD_M
 .PHONY: sband
 sband: check-board download-libraries ## Install S-band passthrough to board
 	@echo "Installing S-band passthrough to $(BOARD_MOUNT_POINT)..."
-	@cp boot.py $(BOARD_MOUNT_POINT)/boot.py
-	@cp code-sband.py $(BOARD_MOUNT_POINT)/code.py
-	@cp -r lib $(BOARD_MOUNT_POINT)/
+	@rm -f $(BOARD_MOUNT_POINT)/code.py > /dev/null 2>&1 || true
+	@rsync -avh config.json boot.py lib --exclude=".*" --exclude="__pycache__" $(BOARD_MOUNT_POINT)/ --delete --times --checksum
+	@rsync -avh code-sband.py $(BOARD_MOUNT_POINT)/code.py --times --checksum
 	@echo "S-band passthrough installed successfully!"
 
 .PHONY: lora
 lora: check-board download-libraries ## Install LoRa passthrough to board
 	@echo "Installing LoRa passthrough to $(BOARD_MOUNT_POINT)..."
-	@cp boot.py $(BOARD_MOUNT_POINT)/boot.py
-	@cp code-lora.py $(BOARD_MOUNT_POINT)/code.py
-	@cp -r lib $(BOARD_MOUNT_POINT)/
+	@rm -f $(BOARD_MOUNT_POINT)/code.py > /dev/null 2>&1 || true
+	@rsync -avh config.json boot.py lib --exclude=".*" --exclude="__pycache__" $(BOARD_MOUNT_POINT)/ --delete --times --checksum
+	@rsync -avh code-lora.py $(BOARD_MOUNT_POINT)/code.py --times --checksum
 	@echo "LoRa passthrough installed successfully!"
 
 .PHONY: check-board
@@ -58,6 +58,24 @@ download-libraries: uv ## Download CircuitPython libraries needed for passthroug
 	@rm -rf lib/*.dist-info
 	@rm -rf lib/.lock
 	@echo "Libraries downloaded successfully!"
+
+CIRCUIT_PYTHON ?= ./firmware.uf2
+BOARD ?=
+
+.PHONY: circuit-python
+circuit-python: ## Download Circuit Python firmware. Usage: make circuit-python BOARD={v5a|v5b|v5c|v5d}
+	@if [ -z "$(BOARD)" ]; then \
+		echo "Error: BOARD is not set"; \
+		echo "Usage: make circuit-python BOARD={v5a|v5b|v5c|v5d}"; \
+		exit 1; \
+	fi
+	@case "$(BOARD)" in \
+		v5a|v5b|v5c|v5d) ;; \
+		*) echo "Error: Invalid board '$(BOARD)'. Must be one of: v5a, v5b, v5c, v5d"; exit 1;; \
+	esac
+	@echo "Downloading Circuit Python firmware for board $(BOARD)..."
+	@curl -o $(CIRCUIT_PYTHON) -fsSL https://raw.githubusercontent.com/proveskit/flight_controller_board/main/Firmware/FC_FIRM_$(BOARD)_V1.uf2
+	@echo "Firmware downloaded successfully to $(CIRCUIT_PYTHON)"
 
 .PHONY: clean
 clean: ## Remove downloaded libraries
